spring:
  application:
    name: menstruation-equality-map
  datasource:
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
#    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menstruation_equity_map?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password:
  swagger:
    title: menstruation-equality-map
    description: menstruation-equality-map
  jpa:
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: estellayuxin@gmail.com
    password: vvubptqalrgrqznt
    receivers: yuxinh20@uci.edu,ruiyanm@uci.edu
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false


google:
  api-key: AIzaSyDL0gcQf5NFWRFZdXgUtatPoOxE5JaxdJY
  # get building's latitude and longitude
  geoUrl: https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=%s
  distance-matrix: https://maps.googleapis.com/maps/api/distancematrix/json?origins=%s&destinations=%s&key=%s
server:
qrcode:
  url: http://localhost:3000/report?
refill:
  url: http://localhost:8080/report-refill?restroom_id=
