DROP TABLE IF EXISTS `restroom`;

CREATE TABLE `restroom` (
    `id` int NOT NULL AUTO_INCREMENT,
    `building_id` int NOT NULL DEFAULT '0',
    `floor_name` varchar(200) NOT NULL,
    `room_num` varchar(200) NOT NULL,
    `product_status` int NOT NULL DEFAULT '1',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- add column building_num
alter table restroom
add building_name varchar(200);

INSERT INTO restroom (
    building_name,
    floor_name,
    room_num)
VALUES
('Admin Modular ','1','160 A'),
('Aldrich Hall  ALH','1','106'),
('Aldrich Hall  ALH','2','214'),
('Anteater Instruction & Research Building  AIRB','1','1141'),
('Anteater Learning Pavillion','1','N/A'),
('Anteater Learning Pavillion','2','N/A'),
('Anteater Learning Pavillion','3','N/A'),
('Arboretum','1','N/A'),
('Art Studio   ART','1','169'),
('Arts Instruction & Technology Resourse Center  AITR','1','192B'),
('Beckman Laser Institute   BLI','1','C104'),
('Berk Hall   BH','1','204'),
('Biological Sciences Admin.  BSA','1','112'),
('Biological Sciences III','1','1604'),
('Biological Sciences III','1','1002'),
('Biological Sciences III','1','1206'),
('Bonney Research Laboratory   BRL','1','N/A'),
('Bren Hall  DBH','1','1414'),
('Building Services Bldg.  G5','1','103D'),
('Calif.Inst. For Telecom & Info. Tech.  Calit 2','1','1201'),
('Calif.Inst. For Telecom & Info. Tech.  Calit 2','1','1004'),
('Central Plant    CP','2','2331'),
('Claire Trevor Theater   CTT','B','B03A'),
('Claire Trevor Theater   CTT','B','B03B'),
('Claire Trevor Theater   CTT','B','B17A'),
('Sue And Bill Gross Hall Nursing and Health Science','1','N/A'),
('Sue And Bill Gross Hall Nursing and Health Science','1','N/A'),
('Susan And Henry Samueli College of Health Sciences','1','N/A'),
('Susan And Henry Samueli College of Health Sciences','1','N/A'),
('Crawford Hall   CH','1','1222'),
('Croul Hall    CRH','1','1303'),
('Disability Services Center','1','116'),
('Drama Building   DRA','1','113'),
('Education (Berkely Pl. N.)','1','1006'),
('Education (Berkely Pl. N.)','2','2105'),
('Engineering  & Computing Trailer  ECT','1','125'),
('Engineering Gateway  EG','1','E1126'),
('Engineering Hall','1','1101'),
('Engineering Laboratory Facility   ELF','1','128'),
('Engineering Lecture Hall ELH','1','102'),
('Engineering Tower   ET','4','430'),
('Enviromental Health & Safety','1','111'),
('Gateway Study Center  GC','1','1028G'),
('Gateway Study Center  GC','2','2000I'),
('Gillespie Neuroscience Research Facility   GNRF','1','1145'),
('Greenhouse','1','107'),
('Greenhouse','1','109A'),
('Grounds Maintenance Facility  G5','1','106'),
('Gross Hall','1','1021'),
('Hewitt Research Hall   HRH','1','1006'),
('Hewitt Research Hall   HRH','1','1123'),
('Hewitt Research Hall   HRH','1','1133'),
('Humanities Gateway   HG','1','1103'),
('Humanities Hall  HH','1','123'),
('Humanities Hall  HH','1','122'),
('Humanities Hall  HH','2','272'),
('Humanities Instructional Bldg.  HIB','1','117'),
('Intercollegiate Athletics Building','1','N/A'),
('Information & Computer Science  ICS','1','166'),
('Information & Computer Science  ICS','2','239'),
('Information & Computer Science 2   ICS2','1','118'),
('Information & Computer Science 2   ICS2','2','230'),
('Information & Computer Science 2   ICS2','2','222'),
('Interim Office Building','1','138'),
('Irvine Hall   IH','1','124'),
('Irvine Hall   IH','1','146'),
('Irvine Hall   IH','1','185'),
('Irvine Hall   IH','1','245'),
('Irvine Hall   IH','1','229'),
('Irvine Hall   IH','1','276'),
('Interdisciplinary Science and Engineering Building','1','N/A'),
('Interdisciplinary Science and Engineering Building','1','N/A'),
('Krieger Hall   KH','1','114'),
('Krieger Hall   KH','2','214'),
('Langson Library  LLIB','2','260'),
('Langson Library  LLIB','2','216'),
('Law (Berkeley Pl. S)','2','2300'),
('McGaugh Hall   MH','1','1225'),
('Medical Education Bldg.','1','1103'),
('Medical Sciences A  Annex','1','N/A'),
('Medical Sciences B   MS-B','1','B143'),
('Medical Sciences B   MS-B','2','B243'),
('Medical Sciences D    MS-D','3','D343'),
('Medical Sciences D    MS-D','4','D443'),
('Medical Sciences E    MS-E','1','E104'),
('Medical Surge I   MS1','1','115'),
('Medical Surge II   MS2','1','325B'),
('Medical Surge II   MS2','1','312A'),
('Medical Surge II   MS2','1','361C'),
('Mesa Arts Building   MAB','1','122'),
('Mesa Arts Building   MAB','2','232'),
('Mesa Office Building  MOB','1','N/A'),
('Multipurpose Academic & Administration Bldg.','1','118'),
('Music & Media Building   MM','1','114'),
('Music & Media Building   MM','2','212'),
('Natural Sciences I   NS1','1','1102'),
('Natural Sciences I   NS1','2','2102'),
('Natural Sciences II  NS2','1','1004'),
('Performance Studios  PSTU','1','1120'),
('Physical Sciences Classroom Building  PSCB','1','C105'),
('Physical Sciences High Bay ','1','1920'),
('Physical Sciences Lecture Hall  PSLH  ','1','L009'),
('Plumwood House    PH','1','143'),
('Production Studio','1','136'),
('Production Studio','1','1205'),
('Production Studio','1','1208'),
('Qureshey Research Laboratory  QRL','2','210C'),
('Reines Hall  RH','1','B011'),
('Robert Winifred Smith','1','190'),
('Robert Winifred Smith','1','185'),
('Robert Winifred Smith','1','183'),
('Rockwell Engineering Center  REC','1','104'),
('Rowland Hall   RH','1','141'),
('School Of Business 1','1','N/A'),
('School Of Business 2','1','110'),
('Science Library  SLIB','1','106'),
('Science Library  SLIB','1','N/A'),
('Science Library  SLIB','1','N/A'),
('Science Library  SLIB','1','N/A'),
('Smith Hall   WSH','1','187'),
('Social & Behavioral Sciences','1','1105'),
('Social Ecology I SE','1','137'),
('Social Ecology II  SE2','1','1343'),
('Social Science Laboratory  SSL','1','103'),
('Social Science Laboratory  SSL','2','201'),
('Social Science Plaza A   SSPA','1','1152'),
('Social Science Plaza B   SSPB','1','1230'),
('Social Science Tower  SST','1','193'),
('Sprague Hall   SPH','1','119B'),
('Steinhaus Hall  SH','1','181'),
('Steinhaus Hall  SH','1','118'),
('Student Ser I,  - SS1  SS2','1','105'),
('Student Ser I,  II - SS1  SS2','1','1030'),
('Studio Four','1','N/A'),
('Tamkin Student Lecture Bldg.','1','F111'),
('Track & Field House ','1','N/A'),
('Student Center','G building 4th floor','467'),
('Student Center','G building 3th floor','316'),
('Student Center','G building 3th floor','315'),
('Student Center','G building 2th floor','207'),
('Student Center','A building 3th floor','304'),
('Student Center','A building 2th floor','227'),
('Student Center','A building 1th floor','114'),
('Student Center','C building 1th floor','120'),
('Student Center','C building 1th floor','100'),
('Cross Cultural Center','2','202'),
('Cross Cultural Center','2','203'),
('Cross Cultural Center','1','115');

-- add values for the building_id column
update restroom inner join
(select r.id as restroom_id, b.id as building_id
    from building as b, restroom as r
    where b.building_name = r.building_name
    order by r.id) as t1
on restroom.id = t1.restroom_id
set restroom.`building_id` = t1.`building_id`;

-- corner case: change building_id for restroom 113
-- update restroom
-- set building_id = 11
-- where restroom_id = 113;

-- delete building_num column
alter table restroom
drop column building_name;

-- unset default value for building_id
ALTER TABLE `restroom`
CHANGE COLUMN `building_id` `building_id` INT NOT NULL ;
